# Generated by Django 3.1.6 on 2021-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_education_experience_profile_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
