# Generated by Django 3.1.6 on 2021-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
