# Generated by Django 3.1.6 on 2021-06-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210603_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
