# Generated by Django 3.1.6 on 2021-06-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210604_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('institute', models.TextField()),
                ('completed_on', models.DateField()),
                ('certi_link', models.URLField(null=True)),
            ],
            options={
                'ordering': ('completed_on',),
            },
        ),
    ]
