# Generated by Django 3.1.6 on 2021-05-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210529_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='the_year',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='the_year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
